export let fakeApiData = [
    {
      validator: "John Doe",
      status: "Active",
      validatorHash: "0xabc123",
      stakedMind: 1000,
      earnedReward: 500,
      totalValidatedBlock: 10000,
    },
    {
      validator: "Jane Smith",
      status: "Inactive",
      validatorHash: "0xdef456",
      stakedMind: 2000,
      earnedReward: 800,
      totalValidatedBlock: 15000,
    },
    {
      validator: "Alice Johnson",
      status: "Active",
      validatorHash: "0xghi789",
      stakedMind: 3000,
      earnedReward: 1200,
      totalValidatedBlock: 20000,
    },
    // Add more objects here with fake data
    {
      validator: "Bob Thompson",
      status: "Active",
      validatorHash: "0xjkl012",
      stakedMind: 2500,
      earnedReward: 1000,
      totalValidatedBlock: 18000,
    },
    {
      validator: "Eve Davis",
      status: "Inactive",
      validatorHash: "0xmno345",
      stakedMind: 1500,
      earnedReward: 700,
      totalValidatedBlock: 12000,
    },
    // Add more objects here with fake data
    {
      validator: "Michael Wilson",
      status: "Active",
      validatorHash: "0xpqr678",
      stakedMind: 1800,
      earnedReward: 900,
      totalValidatedBlock: 15000,
    },
    {
      validator: "Sarah Adams",
      status: "Active",
      validatorHash: "0xstu901",
      stakedMind: 2200,
      earnedReward: 1100,
      totalValidatedBlock: 19000,
    },
    // Add more objects here with fake data
    {
      validator: "David Brown",
      status: "Inactive",
      validatorHash: "0xvwx234",
      stakedMind: 1300,
      earnedReward: 600,
      totalValidatedBlock: 10000,
    },
    {
      validator: "Olivia Green",
      status: "Active",
      validatorHash: "0xyza567",
      stakedMind: 2800,
      earnedReward: 1400,
      totalValidatedBlock: 22000,
    },
    {
        validator: "John Doe",
        status: "Active",
        validatorHash: "0xabc123",
        stakedMind: 1000,
        earnedReward: 500,
        totalValidatedBlock: 10000,
      },
      {
        validator: "Jane Smith",
        status: "Inactive",
        validatorHash: "0xdef456",
        stakedMind: 2000,
        earnedReward: 800,
        totalValidatedBlock: 15000,
      },
      {
        validator: "Alice Johnson",
        status: "Active",
        validatorHash: "0xghi789",
        stakedMind: 3000,
        earnedReward: 1200,
        totalValidatedBlock: 20000,
      },
      // Add more objects here with fake data
      {
        validator: "Bob Thompson",
        status: "Active",
        validatorHash: "0xjkl012",
        stakedMind: 2500,
        earnedReward: 1000,
        totalValidatedBlock: 18000,
      },
      {
        validator: "Eve Davis",
        status: "Inactive",
        validatorHash: "0xmno345",
        stakedMind: 1500,
        earnedReward: 700,
        totalValidatedBlock: 12000,
      },
      // Add more objects here with fake data
      {
        validator: "Michael Wilson",
        status: "Active",
        validatorHash: "0xpqr678",
        stakedMind: 1800,
        earnedReward: 900,
        totalValidatedBlock: 15000,
      },
      {
        validator: "Sarah Adams",
        status: "Active",
        validatorHash: "0xstu901",
        stakedMind: 2200,
        earnedReward: 1100,
        totalValidatedBlock: 19000,
      },
      // Add more objects here with fake data
      {
        validator: "David Brown",
        status: "Inactive",
        validatorHash: "0xvwx234",
        stakedMind: 1300,
        earnedReward: 600,
        totalValidatedBlock: 10000,
      },
      {
        validator: "Olivia Green",
        status: "Active",
        validatorHash: "0xyza567",
        stakedMind: 2800,
        earnedReward: 1400,
        totalValidatedBlock: 22000,
      },
      {
        validator: "John Doe",
        status: "Active",
        validatorHash: "0xabc123",
        stakedMind: 1000,
        earnedReward: 500,
        totalValidatedBlock: 10000,
      },
      {
        validator: "Jane Smith",
        status: "Inactive",
        validatorHash: "0xdef456",
        stakedMind: 2000,
        earnedReward: 800,
        totalValidatedBlock: 15000,
      },
      {
        validator: "Alice Johnson",
        status: "Active",
        validatorHash: "0xghi789",
        stakedMind: 3000,
        earnedReward: 1200,
        totalValidatedBlock: 20000,
      },
      // Add more objects here with fake data
      {
        validator: "Bob Thompson",
        status: "Active",
        validatorHash: "0xjkl012",
        stakedMind: 2500,
        earnedReward: 1000,
        totalValidatedBlock: 18000,
      },
      {
        validator: "Eve Davis",
        status: "Inactive",
        validatorHash: "0xmno345",
        stakedMind: 1500,
        earnedReward: 700,
        totalValidatedBlock: 12000,
      },
      // Add more objects here with fake data
      {
        validator: "Michael Wilson",
        status: "Active",
        validatorHash: "0xpqr678",
        stakedMind: 1800,
        earnedReward: 900,
        totalValidatedBlock: 15000,
      },
      {
        validator: "Sarah Adams",
        status: "Active",
        validatorHash: "0xstu901",
        stakedMind: 2200,
        earnedReward: 1100,
        totalValidatedBlock: 19000,
      },
      // Add more objects here with fake data
      {
        validator: "David Brown",
        status: "Inactive",
        validatorHash: "0xvwx234",
        stakedMind: 1300,
        earnedReward: 600,
        totalValidatedBlock: 10000,
      },
      {
        validator: "Olivia Green",
        status: "Active",
        validatorHash: "0xyza567",
        stakedMind: 2800,
        earnedReward: 1400,
        totalValidatedBlock: 22000,
      },
      {
          validator: "John Doe",
          status: "Active",
          validatorHash: "0xabc123",
          stakedMind: 1000,
          earnedReward: 500,
          totalValidatedBlock: 10000,
        },
        {
          validator: "Jane Smith",
          status: "Inactive",
          validatorHash: "0xdef456",
          stakedMind: 2000,
          earnedReward: 800,
          totalValidatedBlock: 15000,
        },
        {
          validator: "Alice Johnson",
          status: "Active",
          validatorHash: "0xghi789",
          stakedMind: 3000,
          earnedReward: 1200,
          totalValidatedBlock: 20000,
        },
        // Add more objects here with fake data
        {
          validator: "Bob Thompson",
          status: "Active",
          validatorHash: "0xjkl012",
          stakedMind: 2500,
          earnedReward: 1000,
          totalValidatedBlock: 18000,
        },
        {
          validator: "Eve Davis",
          status: "Inactive",
          validatorHash: "0xmno345",
          stakedMind: 1500,
          earnedReward: 700,
          totalValidatedBlock: 12000,
        },
        // Add more objects here with fake data
        {
          validator: "Michael Wilson",
          status: "Active",
          validatorHash: "0xpqr678",
          stakedMind: 1800,
          earnedReward: 900,
          totalValidatedBlock: 15000,
        },
        {
          validator: "Sarah Adams",
          status: "Active",
          validatorHash: "0xstu901",
          stakedMind: 2200,
          earnedReward: 1100,
          totalValidatedBlock: 19000,
        },
        // Add more objects here with fake data
        {
          validator: "David Brown",
          status: "Inactive",
          validatorHash: "0xvwx234",
          stakedMind: 1300,
          earnedReward: 600,
          totalValidatedBlock: 10000,
        },
        {
          validator: "Olivia Green",
          status: "Active",
          validatorHash: "0xyza567",
          stakedMind: 2800,
          earnedReward: 1400,
          totalValidatedBlock: 22000,
        },
        {
          validator: "John Doe",
          status: "Active",
          validatorHash: "0xabc123",
          stakedMind: 1000,
          earnedReward: 500,
          totalValidatedBlock: 10000,
        },
        {
          validator: "Jane Smith",
          status: "Inactive",
          validatorHash: "0xdef456",
          stakedMind: 2000,
          earnedReward: 800,
          totalValidatedBlock: 15000,
        },
        {
          validator: "Alice Johnson",
          status: "Active",
          validatorHash: "0xghi789",
          stakedMind: 3000,
          earnedReward: 1200,
          totalValidatedBlock: 20000,
        },
        // Add more objects here with fake data
        {
          validator: "Bob Thompson",
          status: "Active",
          validatorHash: "0xjkl012",
          stakedMind: 2500,
          earnedReward: 1000,
          totalValidatedBlock: 18000,
        },
        {
          validator: "Eve Davis",
          status: "Inactive",
          validatorHash: "0xmno345",
          stakedMind: 1500,
          earnedReward: 700,
          totalValidatedBlock: 12000,
        },
        // Add more objects here with fake data
        {
          validator: "Michael Wilson",
          status: "Active",
          validatorHash: "0xpqr678",
          stakedMind: 1800,
          earnedReward: 900,
          totalValidatedBlock: 15000,
        },
        {
          validator: "Sarah Adams",
          status: "Active",
          validatorHash: "0xstu901",
          stakedMind: 2200,
          earnedReward: 1100,
          totalValidatedBlock: 19000,
        },
        // Add more objects here with fake data
        {
          validator: "David Brown",
          status: "Inactive",
          validatorHash: "0xvwx234",
          stakedMind: 1300,
          earnedReward: 600,
          totalValidatedBlock: 10000,
        },
        {
          validator: "Olivia Green",
          status: "Active",
          validatorHash: "0xyza567",
          stakedMind: 2800,
          earnedReward: 1400,
          totalValidatedBlock: 22000,
        },
        {
            validator: "John Doe",
            status: "Active",
            validatorHash: "0xabc123",
            stakedMind: 1000,
            earnedReward: 500,
            totalValidatedBlock: 10000,
          },
          {
            validator: "Jane Smith",
            status: "Inactive",
            validatorHash: "0xdef456",
            stakedMind: 2000,
            earnedReward: 800,
            totalValidatedBlock: 15000,
          },
          {
            validator: "Alice Johnson",
            status: "Active",
            validatorHash: "0xghi789",
            stakedMind: 3000,
            earnedReward: 1200,
            totalValidatedBlock: 20000,
          },
          // Add more objects here with fake data
          {
            validator: "Bob Thompson",
            status: "Active",
            validatorHash: "0xjkl012",
            stakedMind: 2500,
            earnedReward: 1000,
            totalValidatedBlock: 18000,
          },
          {
            validator: "Eve Davis",
            status: "Inactive",
            validatorHash: "0xmno345",
            stakedMind: 1500,
            earnedReward: 700,
            totalValidatedBlock: 12000,
          },
          // Add more objects here with fake data
          {
            validator: "Michael Wilson",
            status: "Active",
            validatorHash: "0xpqr678",
            stakedMind: 1800,
            earnedReward: 900,
            totalValidatedBlock: 15000,
          },
          {
            validator: "Sarah Adams",
            status: "Active",
            validatorHash: "0xstu901",
            stakedMind: 2200,
            earnedReward: 1100,
            totalValidatedBlock: 19000,
          },
          // Add more objects here with fake data
          {
            validator: "David Brown",
            status: "Inactive",
            validatorHash: "0xvwx234",
            stakedMind: 1300,
            earnedReward: 600,
            totalValidatedBlock: 10000,
          },
          {
            validator: "Olivia Green",
            status: "Active",
            validatorHash: "0xyza567",
            stakedMind: 2800,
            earnedReward: 1400,
            totalValidatedBlock: 22000,
          },
          {
            validator: "John Doe",
            status: "Active",
            validatorHash: "0xabc123",
            stakedMind: 1000,
            earnedReward: 500,
            totalValidatedBlock: 10000,
          },
          {
            validator: "Jane Smith",
            status: "Inactive",
            validatorHash: "0xdef456",
            stakedMind: 2000,
            earnedReward: 800,
            totalValidatedBlock: 15000,
          },
          {
            validator: "Alice Johnson",
            status: "Active",
            validatorHash: "0xghi789",
            stakedMind: 3000,
            earnedReward: 1200,
            totalValidatedBlock: 20000,
          },
          // Add more objects here with fake data
          {
            validator: "Bob Thompson",
            status: "Active",
            validatorHash: "0xjkl012",
            stakedMind: 2500,
            earnedReward: 1000,
            totalValidatedBlock: 18000,
          },
          {
            validator: "Eve Davis",
            status: "Inactive",
            validatorHash: "0xmno345",
            stakedMind: 1500,
            earnedReward: 700,
            totalValidatedBlock: 12000,
          },
          // Add more objects here with fake data
          {
            validator: "Michael Wilson",
            status: "Active",
            validatorHash: "0xpqr678",
            stakedMind: 1800,
            earnedReward: 900,
            totalValidatedBlock: 15000,
          },
          {
            validator: "Sarah Adams",
            status: "Active",
            validatorHash: "0xstu901",
            stakedMind: 2200,
            earnedReward: 1100,
            totalValidatedBlock: 19000,
          },
          // Add more objects here with fake data
          {
            validator: "David Brown",
            status: "Inactive",
            validatorHash: "0xvwx234",
            stakedMind: 1300,
            earnedReward: 600,
            totalValidatedBlock: 10000,
          },
          {
            validator: "Olivia Green",
            status: "Active",
            validatorHash: "0xyza567",
            stakedMind: 2800,
            earnedReward: 1400,
            totalValidatedBlock: 22000,
          },
          {
              validator: "John Doe",
              status: "Active",
              validatorHash: "0xabc123",
              stakedMind: 1000,
              earnedReward: 500,
              totalValidatedBlock: 10000,
            },
            {
              validator: "Jane Smith",
              status: "Inactive",
              validatorHash: "0xdef456",
              stakedMind: 2000,
              earnedReward: 800,
              totalValidatedBlock: 15000,
            },
            {
              validator: "Alice Johnson",
              status: "Active",
              validatorHash: "0xghi789",
              stakedMind: 3000,
              earnedReward: 1200,
              totalValidatedBlock: 20000,
            },
            // Add more objects here with fake data
            {
              validator: "Bob Thompson",
              status: "Active",
              validatorHash: "0xjkl012",
              stakedMind: 2500,
              earnedReward: 1000,
              totalValidatedBlock: 18000,
            },
            {
              validator: "Eve Davis",
              status: "Inactive",
              validatorHash: "0xmno345",
              stakedMind: 1500,
              earnedReward: 700,
              totalValidatedBlock: 12000,
            },
            // Add more objects here with fake data
            {
              validator: "Michael Wilson",
              status: "Active",
              validatorHash: "0xpqr678",
              stakedMind: 1800,
              earnedReward: 900,
              totalValidatedBlock: 15000,
            },
            {
              validator: "Sarah Adams",
              status: "Active",
              validatorHash: "0xstu901",
              stakedMind: 2200,
              earnedReward: 1100,
              totalValidatedBlock: 19000,
            },
            // Add more objects here with fake data
            {
              validator: "David Brown",
              status: "Inactive",
              validatorHash: "0xvwx234",
              stakedMind: 1300,
              earnedReward: 600,
              totalValidatedBlock: 10000,
            },
            {
              validator: "Olivia Green",
              status: "Active",
              validatorHash: "0xyza567",
              stakedMind: 2800,
              earnedReward: 1400,
              totalValidatedBlock: 22000,
            },
            {
              validator: "John Doe",
              status: "Active",
              validatorHash: "0xabc123",
              stakedMind: 1000,
              earnedReward: 500,
              totalValidatedBlock: 10000,
            },
            {
              validator: "Jane Smith",
              status: "Inactive",
              validatorHash: "0xdef456",
              stakedMind: 2000,
              earnedReward: 800,
              totalValidatedBlock: 15000,
            },
            {
              validator: "Alice Johnson",
              status: "Active",
              validatorHash: "0xghi789",
              stakedMind: 3000,
              earnedReward: 1200,
              totalValidatedBlock: 20000,
            },
            // Add more objects here with fake data
            {
              validator: "Bob Thompson",
              status: "Active",
              validatorHash: "0xjkl012",
              stakedMind: 2500,
              earnedReward: 1000,
              totalValidatedBlock: 18000,
            },
            {
              validator: "Eve Davis",
              status: "Inactive",
              validatorHash: "0xmno345",
              stakedMind: 1500,
              earnedReward: 700,
              totalValidatedBlock: 12000,
            },
            // Add more objects here with fake data
            {
              validator: "Michael Wilson",
              status: "Active",
              validatorHash: "0xpqr678",
              stakedMind: 1800,
              earnedReward: 900,
              totalValidatedBlock: 15000,
            },
            {
              validator: "Sarah Adams",
              status: "Active",
              validatorHash: "0xstu901",
              stakedMind: 2200,
              earnedReward: 1100,
              totalValidatedBlock: 19000,
            },
            // Add more objects here with fake data
            {
              validator: "David Brown",
              status: "Inactive",
              validatorHash: "0xvwx234",
              stakedMind: 1300,
              earnedReward: 600,
              totalValidatedBlock: 10000,
            },
            {
              validator: "Olivia Green",
              status: "Active",
              validatorHash: "0xyza567",
              stakedMind: 2800,
              earnedReward: 1400,
              totalValidatedBlock: 22000,
            },
            {
                validator: "John Doe",
                status: "Active",
                validatorHash: "0xabc123",
                stakedMind: 1000,
                earnedReward: 500,
                totalValidatedBlock: 10000,
              },
              {
                validator: "Jane Smith",
                status: "Inactive",
                validatorHash: "0xdef456",
                stakedMind: 2000,
                earnedReward: 800,
                totalValidatedBlock: 15000,
              },
              {
                validator: "Alice Johnson",
                status: "Active",
                validatorHash: "0xghi789",
                stakedMind: 3000,
                earnedReward: 1200,
                totalValidatedBlock: 20000,
              },
              // Add more objects here with fake data
              {
                validator: "Bob Thompson",
                status: "Active",
                validatorHash: "0xjkl012",
                stakedMind: 2500,
                earnedReward: 1000,
                totalValidatedBlock: 18000,
              },
              {
                validator: "Eve Davis",
                status: "Inactive",
                validatorHash: "0xmno345",
                stakedMind: 1500,
                earnedReward: 700,
                totalValidatedBlock: 12000,
              },
              // Add more objects here with fake data
              {
                validator: "Michael Wilson",
                status: "Active",
                validatorHash: "0xpqr678",
                stakedMind: 1800,
                earnedReward: 900,
                totalValidatedBlock: 15000,
              },
              {
                validator: "Sarah Adams",
                status: "Active",
                validatorHash: "0xstu901",
                stakedMind: 2200,
                earnedReward: 1100,
                totalValidatedBlock: 19000,
              },
              // Add more objects here with fake data
              {
                validator: "David Brown",
                status: "Inactive",
                validatorHash: "0xvwx234",
                stakedMind: 1300,
                earnedReward: 600,
                totalValidatedBlock: 10000,
              },
              {
                validator: "Olivia Green",
                status: "Active",
                validatorHash: "0xyza567",
                stakedMind: 2800,
                earnedReward: 1400,
                totalValidatedBlock: 22000,
              },
              {
                validator: "John Doe",
                status: "Active",
                validatorHash: "0xabc123",
                stakedMind: 1000,
                earnedReward: 500,
                totalValidatedBlock: 10000,
              },
              {
                validator: "Jane Smith",
                status: "Inactive",
                validatorHash: "0xdef456",
                stakedMind: 2000,
                earnedReward: 800,
                totalValidatedBlock: 15000,
              },
              {
                validator: "Alice Johnson",
                status: "Active",
                validatorHash: "0xghi789",
                stakedMind: 3000,
                earnedReward: 1200,
                totalValidatedBlock: 20000,
              },
              // Add more objects here with fake data
              {
                validator: "Bob Thompson",
                status: "Active",
                validatorHash: "0xjkl012",
                stakedMind: 2500,
                earnedReward: 1000,
                totalValidatedBlock: 18000,
              },
              {
                validator: "Eve Davis",
                status: "Inactive",
                validatorHash: "0xmno345",
                stakedMind: 1500,
                earnedReward: 700,
                totalValidatedBlock: 12000,
              },
              // Add more objects here with fake data
              {
                validator: "Michael Wilson",
                status: "Active",
                validatorHash: "0xpqr678",
                stakedMind: 1800,
                earnedReward: 900,
                totalValidatedBlock: 15000,
              },
              {
                validator: "Sarah Adams",
                status: "Active",
                validatorHash: "0xstu901",
                stakedMind: 2200,
                earnedReward: 1100,
                totalValidatedBlock: 19000,
              },
              // Add more objects here with fake data
              {
                validator: "David Brown",
                status: "Inactive",
                validatorHash: "0xvwx234",
                stakedMind: 1300,
                earnedReward: 600,
                totalValidatedBlock: 10000,
              },
              {
                validator: "Olivia Green",
                status: "Active",
                validatorHash: "0xyza567",
                stakedMind: 2800,
                earnedReward: 1400,
                totalValidatedBlock: 22000,
              },
              {
                  validator: "John Doe",
                  status: "Active",
                  validatorHash: "0xabc123",
                  stakedMind: 1000,
                  earnedReward: 500,
                  totalValidatedBlock: 10000,
                },
                {
                  validator: "Jane Smith",
                  status: "Inactive",
                  validatorHash: "0xdef456",
                  stakedMind: 2000,
                  earnedReward: 800,
                  totalValidatedBlock: 15000,
                },
                {
                  validator: "Alice Johnson",
                  status: "Active",
                  validatorHash: "0xghi789",
                  stakedMind: 3000,
                  earnedReward: 1200,
                  totalValidatedBlock: 20000,
                },
                // Add more objects here with fake data
                {
                  validator: "Bob Thompson",
                  status: "Active",
                  validatorHash: "0xjkl012",
                  stakedMind: 2500,
                  earnedReward: 1000,
                  totalValidatedBlock: 18000,
                },
                {
                  validator: "Eve Davis",
                  status: "Inactive",
                  validatorHash: "0xmno345",
                  stakedMind: 1500,
                  earnedReward: 700,
                  totalValidatedBlock: 12000,
                },
                // Add more objects here with fake data
                {
                  validator: "Michael Wilson",
                  status: "Active",
                  validatorHash: "0xpqr678",
                  stakedMind: 1800,
                  earnedReward: 900,
                  totalValidatedBlock: 15000,
                },
                {
                  validator: "Sarah Adams",
                  status: "Active",
                  validatorHash: "0xstu901",
                  stakedMind: 2200,
                  earnedReward: 1100,
                  totalValidatedBlock: 19000,
                },
                // Add more objects here with fake data
                {
                  validator: "David Brown",
                  status: "Inactive",
                  validatorHash: "0xvwx234",
                  stakedMind: 1300,
                  earnedReward: 600,
                  totalValidatedBlock: 10000,
                },
                {
                  validator: "Olivia Green",
                  status: "Active",
                  validatorHash: "0xyza567",
                  stakedMind: 2800,
                  earnedReward: 1400,
                  totalValidatedBlock: 22000,
                },
                {
                  validator: "John Doe",
                  status: "Active",
                  validatorHash: "0xabc123",
                  stakedMind: 1000,
                  earnedReward: 500,
                  totalValidatedBlock: 10000,
                },
                {
                  validator: "Jane Smith",
                  status: "Inactive",
                  validatorHash: "0xdef456",
                  stakedMind: 2000,
                  earnedReward: 800,
                  totalValidatedBlock: 15000,
                },
                {
                  validator: "Alice Johnson",
                  status: "Active",
                  validatorHash: "0xghi789",
                  stakedMind: 3000,
                  earnedReward: 1200,
                  totalValidatedBlock: 20000,
                },
                // Add more objects here with fake data
                {
                  validator: "Bob Thompson",
                  status: "Active",
                  validatorHash: "0xjkl012",
                  stakedMind: 2500,
                  earnedReward: 1000,
                  totalValidatedBlock: 18000,
                },
                {
                  validator: "Eve Davis",
                  status: "Inactive",
                  validatorHash: "0xmno345",
                  stakedMind: 1500,
                  earnedReward: 700,
                  totalValidatedBlock: 12000,
                },
                // Add more objects here with fake data
                {
                  validator: "Michael Wilson",
                  status: "Active",
                  validatorHash: "0xpqr678",
                  stakedMind: 1800,
                  earnedReward: 900,
                  totalValidatedBlock: 15000,
                },
                {
                  validator: "Sarah Adams",
                  status: "Active",
                  validatorHash: "0xstu901",
                  stakedMind: 2200,
                  earnedReward: 1100,
                  totalValidatedBlock: 19000,
                },
                // Add more objects here with fake data
                {
                  validator: "David Brown",
                  status: "Inactive",
                  validatorHash: "0xvwx234",
                  stakedMind: 1300,
                  earnedReward: 600,
                  totalValidatedBlock: 10000,
                },
                {
                  validator: "Olivia Green",
                  status: "Active",
                  validatorHash: "0xyza567",
                  stakedMind: 2800,
                  earnedReward: 1400,
                  totalValidatedBlock: 22000,
                },
                {
                    validator: "John Doe",
                    status: "Active",
                    validatorHash: "0xabc123",
                    stakedMind: 1000,
                    earnedReward: 500,
                    totalValidatedBlock: 10000,
                  },
                  {
                    validator: "Jane Smith",
                    status: "Inactive",
                    validatorHash: "0xdef456",
                    stakedMind: 2000,
                    earnedReward: 800,
                    totalValidatedBlock: 15000,
                  },
                  {
                    validator: "Alice Johnson",
                    status: "Active",
                    validatorHash: "0xghi789",
                    stakedMind: 3000,
                    earnedReward: 1200,
                    totalValidatedBlock: 20000,
                  },
                  // Add more objects here with fake data
                  {
                    validator: "Bob Thompson",
                    status: "Active",
                    validatorHash: "0xjkl012",
                    stakedMind: 2500,
                    earnedReward: 1000,
                    totalValidatedBlock: 18000,
                  },
                  {
                    validator: "Eve Davis",
                    status: "Inactive",
                    validatorHash: "0xmno345",
                    stakedMind: 1500,
                    earnedReward: 700,
                    totalValidatedBlock: 12000,
                  },
                  // Add more objects here with fake data
                  {
                    validator: "Michael Wilson",
                    status: "Active",
                    validatorHash: "0xpqr678",
                    stakedMind: 1800,
                    earnedReward: 900,
                    totalValidatedBlock: 15000,
                  },
                  {
                    validator: "Sarah Adams",
                    status: "Active",
                    validatorHash: "0xstu901",
                    stakedMind: 2200,
                    earnedReward: 1100,
                    totalValidatedBlock: 19000,
                  },
                  // Add more objects here with fake data
                  {
                    validator: "David Brown",
                    status: "Inactive",
                    validatorHash: "0xvwx234",
                    stakedMind: 1300,
                    earnedReward: 600,
                    totalValidatedBlock: 10000,
                  },
                  {
                    validator: "Olivia Green",
                    status: "Active",
                    validatorHash: "0xyza567",
                    stakedMind: 2800,
                    earnedReward: 1400,
                    totalValidatedBlock: 22000,
                  },
                  
    // Add more objects here with fake data
  ];